include:
  - template: "Security/SAST.gitlab-ci.yml"
  - project: "dead-zl/infra/ci-cd-templates"
    ref: "main"
    file:
      - "templates/lms-autodeploy.yml"


stages:
  - sast
  - build
  - test
  - push
  - deploy

sast:
  stage: sast
